# Generated by Django 4.2.25 on 2025-10-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
