# Generated by Django 4.2.25 on 2025-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0003_alter_lostitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional direct URL to image', null=True),
        ),
    ]
