# Generated by Django 4.2.25 on 2025-11-05 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0004_founditem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('item_id', models.UUIDField()),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
