# Generated by Django 4.2.25 on 2025-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0006_message_delete_imagefeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='supporting_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
