# Generated by Django 4.2.25 on 2025-12-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0007_alter_claim_supporting_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_description',
            new_name='claimDescription',
        ),
    ]
