# Generated by Django 4.2.25 on 2025-12-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app1', '0008_rename_claim_description_claim_claimdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='admin_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
